### ISSUE TITLE
Runelite Icon missing

### ISSUE THREAD

**Issue by xPaZzyy** [runelite/launcher#110]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The Runelite icon on my desktop and the icon in the appdata both have no icon.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/61637026/183837103-6560ff3b-c9b8-47f4-861f-9fafa7e9517b.png)

**Comment by Adam-** [comment]
Looks like resourcehacker is not working when run on actions and I am having trouble determining why. It is causing both the icon and manifest to not be set correctly. I've changed actions to use rcedit which looks like it is working better 8dab9669917b6797faaba18611f949129a644e81
