### ISSUE TITLE
Re-installing fails after removal of previous device RL was installed on

### ISSUE THREAD

**Issue by oamaok** [runelite/launcher#113]
A while back one of my old harddrives broke down, and I had installed RuneLite on it. Now, once I try to reinstall, some of the previous configuration seems to still be present and it attempts to update/reinstall using the now unexistent path. What I now get is the following error:

![image](https://user-images.githubusercontent.com/3877125/227010024-dfc96279-8a91-4867-94fb-28d1464786da.png)

I did manage fix this by removing the following registry key and its subkeys: `\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RuneLite Launcher_is1`

While the manual fix is relatively easy and I found it quickly, this might not be the case for many, so I hope this will be fixed at some point.

**Comment by oamaok** [comment]
Adding the error message here so if people google it they will find it better:
> The drive or UNC share you selected does not exist or is not accessible. Please select another.

If you arrived here by Google, the quick fix is to run `regedit` and remove the following key and its subkeys: `\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RuneLite Launcher_is1`

**Comment by Adam-** [comment]
fixed in 19f00aefe000cc2c72b559a10e8e60e81d791f1e
