### ISSUE TITLE
Package info URL

### ISSUE THREAD

**Issue by Adamcake** [runelite/launcher#119]
Can runelite please provide a way to _programmatically_ find the latest launcher version, a permalink to the download location, and a file hash. All that information is already found [here](https://github.com/runelite/launcher/releases) but is finnicky for a computer program to parse.

Ideally the info would come from a URL on runelite.net which you can update automatically as part of your build/release process, the contents right now would be:
```
{
 "version": "2.6.9",
 "sha256": "f7588106f897337b4937f8d181c3b352e4c0afd56b2a75b9e6e62b356ede0794",
 "url": "https://github.com/runelite/launcher/releases/download/2.6.9/RuneLite.jar"
}
```
It doesn't necessarily have to be JSON but that's usually the go-to for this type of thing.

The purpose of this would be for direct integration into package managers and game launchers. For example, [flatpak's net.runelite.Runelite](https://github.com/flathub/net.runelite.RuneLite/blob/master/net.runelite.RuneLite.json#L69-L73), which is currently four months out of date, could be kept up-to-date automatically using flatpak-external-data-checker.

**Comment by abextm** [comment]
https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release

https://api.github.com/repos/runelite/launcher/releases/latest

The most recent couple releases have had little to no changes that affect the jar launcher that the flatpak uses, so they don't need to be updated

**Comment by Adamcake** [comment]
Oh this will do perfectly. Thanks
