### ISSUE TITLE
runelite.dmg is acting as corrupt on some macOS versions

### ISSUE THREAD

**Issue by deathbeam** [runelite/launcher#16]
When opening runelite.dmg the image fails to mount and is labeled as corrupt.

**Comment by taterskinss** [comment]
Having the same issue. Running 10.10.5

**Comment by g02h** [comment]
So is there a answer?

**Comment by deathbeam** [comment]
Probably either updating your operating system or tryint to use right-click open instead or simply just using Download for all platforms version.

**Comment by Adam-** [comment]
https://github.com/sindresorhus/create-dmg is used to create the image and says the .dmgs require osx 10.11. https://github.com/sindresorhus/create-dmg/issues/11#issuecomment-301828156 suggests patching `create-dmg` to fix it.

**Comment by deathbeam** [comment]
This should be solved by https://github.com/runelite/launcher/commit/bdfc6f7ca2add226bcec68fecf4472b6d443fe42
