### ISSUE TITLE
macOS client not launching

### ISSUE THREAD

**Issue by deathbeam** [runelite/launcher#17]
MAC client will either just sit on the bar and 'bounce' or it will open the client but stay stuck at 0%.

**Comment by miratepuffin** [comment]
For some reason #1938 is the only thing that popped up on google search, but as this is the open issue I shall repost my solution here.

> I don't know if you are still having this problem, but I just the same thing. Ran the exec inside of the dmg to see what the error was and I didn't have OpenGL installed. (I assume not included in a fresh MacOS install)

> For a quick way to get it, open your terminal and install homebrew (https://brew.sh/) and then type:
>brew install glfw3
>brew install glew

>Should run fine after that.

If this is a problem for multiple people perhaps it should be on the readme, or alternatively included in the dmg

**Comment by Adam-** [comment]
I assume 1.6.0 fixes this.

**Comment by TylerADavis** [comment]
I just downloaded runeLite from runelite.net, dragged the launcher from the .dmg to my applications folder, and when I attempted to open it from the applications folder it just bounced in the dock without anything happening. After letting it bounce for a new minutes I force quit the launcher and attempted to open it again, after which it opened without issue.
