### ISSUE TITLE
Performance: Allow user-configurable choice of HardwareAcceleration in launcher

### ISSUE THREAD

**Issue by BleuSquid** [runelite/launcher#25]
I'm using RL on Linux, and I've found that manually launching without opengl support gives me a significantly higher framerate than when using opengl, however to do so means launching the client manually instead of using the launcher JAR.

CPU: Core i7-3630QM
GPU: Integrated Intel HD Graphics 4000

All other things being equal (player position, launch options, etc):
-Dsun.java2d.opengl=true: average around 16FPS
-Dsun.java2d.opengl=false: average around 40FPS

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by ah42** [comment]
Aha, thank you, that works, but does not seem intuitive.
Would an option in the GUI be possible? (would require restarting the client to take effect, obviously)

**Comment by Abextm** [comment]
There are a number of things that make it difficult for the client to set config options for the launcher without hacks.

**Comment by Adam-** [comment]
this has been added to the configuration gui (open it via --configure)
