### ISSUE TITLE
When launched the process starts but not the application

### ISSUE THREAD

**Issue by nickfrystak** [runelite/launcher#29]
I did a fresh install of the Windows 32 bit and launched the program and it loads the progress bar for loading for just a second then disappears. In task manager Runelite.exe is listed in the processes tab but not in the applications tab. Sound from the program is working as well and is showing up in the sound manager
![image](https://user-images.githubusercontent.com/42226274/43874105-7dfd51ae-9b4f-11e8-9cb3-79d3deaf2581.png)
 Just tested with the .jar launcher as well and i get the same result

**Comment by Yorue** [comment]
did you ever fix it? cause I have the same issue right now.
