### ISSUE TITLE
Client Stuck Loading at 99%

### ISSUE THREAD

**Issue by chip0tle** [runelite/launcher#35]
When trying to launch Runelite for the first time, the client loads quickly up until it stops when loading okhttp-3.7.0.jar at 99%. I've tried deleting the repository, but it did not solve the problem and it gets stuck loading at the same point. My logs only have one line repeated for each time I've tried to launch the client, but it still has yet to fully launch.

Environment (please complete the following information):

Windows 10
RuneLite version: [1.4.20]
Launcher version: [1.4.20]

[launcher.log](https://github.com/runelite/launcher/files/2466168/launcher.log)

**Comment by deathbeam** [comment]
Nothing in here helps? https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by chip0tle** [comment]
@deathbeam I figured it out by going to http://static.runelite.net/bootstrap.json and trying to download the okhttp jar file from the direct link there. My college's network was blocking the download, but I managed to get around it with a proxy. Once I got that file and put it in repository2 the client started fine.
