### ISSUE TITLE
Official Flatpak, deb, and AUR versions

### ISSUE THREAD

**Issue by classicmari** [runelite/launcher#36]
Would it be possible to have official flatpak, .deb, and AUR versions of the RuneLite launcher? It's definitely not absolutely needed since it's already very easy to just get the .jar from the website, but this would let people download the launcher straight from various software managers.

Also please forgive me if I'm misunderstanding how these formats work, I'm still pretty new to the Linux ecosystem.

**Comment by deathbeam** [comment]
I am pretty sure we already have flatpak and aur versions, even though not official

**Comment by classicmari** [comment]
Ah, you're absolutely right about there being unofficial flatpak and aur versions already. Would it step on too many toes to have official versions of those formats?
