### ISSUE TITLE
Runelite Stuck On 0%

### ISSUE THREAD

**Issue by Viision420** [runelite/launcher#42]
Sometimes it starts loading the client up finishes then closes and doesn't open back up.
Most of the times it stays at 0% then abruptly closes and nothing happens.
[launcher.log](https://github.com/runelite/launcher/files/2761978/launcher.log)
This is my log.

**Comment by Adam-** [comment]
This isn't a bug. This just means that the launcher is not able to verify what it is downloading.

**Comment by Viision420** [comment]
> This isn't a bug. This just means that the launcher is not able to verify what it is downloading.

So how do i fix this and start my runelite, Cause it wont launch at all.

**Comment by Viision420** [comment]
Bump?

**Comment by deathbeam** [comment]
If nothing here helps https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client then probably check your firewall/your router settings if it is not intercepting your calls

**Comment by Viision420** [comment]
> If nothing here helps https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client then probably check your firewall/your router settings if it is not intercepting your calls

Im not really sure how i fixed, It last thing i did was Run it as an administrator, As well as adding it to my firewall, Thank you though.
