### ISSUE TITLE
handshake_failure can be fixed with forcing TLSv1.2

### ISSUE THREAD

**Issue by Espionage724** [runelite/launcher#45]
Ran into the handshake_failure error (stuck at 0%) on Fedora Workstation 29 and OpenJDK 11 when trying to run the jar without any flags. Added `-Dhttps.protocols=TLSv1.2` and RL downloaded files and ran fine.

`java -Dhttps.protocols='TLSv1.2' -jar ~/'Downloads/RuneLite.jar'`

I can't imagine TLSv1.2 by itself being an issue on most modern distros, but you could also use TLSv1.1 exclusively, or even have both as a choice:

`-Dhttps.protocols=TLSv1.1,TLSv1.2`

**Comment by Adam-** [comment]
We've discussed this a fair bit in Discord already. Currently we think this is a Java bug specific to tls 1.3 session resumption not working. I don't think anyone has looked into it very closely though.

**Comment by Adam-** [comment]
This was later determined to be a jdk bug with tls 1.3 session resumption in early versions of jdk11. This is no longer applicable as we use later versions.
