### ISSUE TITLE
Runelite Graphical Problem - Launcher

### ISSUE THREAD

**Issue by ruhtain** [runelite/launcher#50]
Hi Guys - So just recently when i open my launcher i've been getting a graphical bug where the log-in screen has white flame and when i textually log in i cant see anything, Anyone else have this problem?

[https://gyazo.com/c272c6f002eccb4f01d4932348adca20](url)

Thanks

**Comment by Hydrox6** [comment]
Looks like you need to disable the GPU plugin

The Discord server's `support` channel is perfect for stuff like this, btw

**Comment by Hydrox6** [comment]
Also this isn't an issue for the launcher, but for the [client](https://github.com/runelite/runelite)

**Comment by ruhtain** [comment]
Thank you, worked.
