### ISSUE TITLE
Multiple Squares with Flame on Manjaro i3

### ISSUE THREAD

**Issue by sangoku116** [runelite/launcher#60]
I am running Manjaro with i3wm and when I launch RuneLite I am getting a bunch of squares with just the flame. I have tried disabling hardware acceleration using 
> echo " --mode=OFF" | sudo tee -a /usr/bin/runelite-launcher

I am using the runelite-launcher package from the AUR. 

[picture here](https://i.gyazo.com/66324315b65e68d81ff23943605fd235.png)

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by sangoku116** [comment]
> https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

I have tried the steps under AUR as stated and did not fix my issue.

**Comment by Abextm** [comment]
run `runelite-launcher --mode=OFF` or `vim $(which runelite-launcher)` and remove the newline before `--mode=OFF`

**Comment by sangoku116** [comment]
Running runelite-launcher --mode=OFF worked. My file looks like this:

`#!/bin/sh
exec java -Dhttps.protocols=TLSv1.2 -jar /usr/share/runelite-launcher/Launcher.jar "$@"
 --mode=OFF
 --mode=OFF
 --mode=OFF
 --mode=OFF
`
What exactly am I supposed to remove ?

**Comment by Abextm** [comment]
remove the last 3 `--mode=OFF`s and the newline after `"$@"` before `--mode=OFF`. Or you can reinstall the package and run now working command on https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by sangoku116** [comment]
Awesome that worked! Thank you for your help.
