### ISSUE TITLE
Launcher Stuck at 0%

### ISSUE THREAD

**Issue by Exatawa** [runelite/launcher#62]
I'm new to this "RuneLite" thing but as soon as I open it up it goes 0% and crashes. My friend is playing it and I would like to join him. Thank you in advance for any help.
[launcher.log](https://github.com/runelite/launcher/files/3197562/launcher.log)
[launcher_2019-05-19.0.log](https://github.com/runelite/launcher/files/3197565/launcher_2019-05-19.0.log)

**Comment by abextm** [comment]
Your java installation is missing certificates, or your connection is being MITM'd, most likely by an (anti?) virus on your machine.

**Comment by Exatawa** [comment]
Hey there is no anitvirus on my computer so im still confused?

**Comment by abextm** [comment]
then you probably have a virus

**Comment by Exatawa** [comment]
But wait if I did wouldn't windows defender notifier me about it?

**Comment by abextm** [comment]
Antiviruses are not omnipotent, so possibly not

**Comment by Exatawa** [comment]
ok then how do i get rid of the virus
