### ISSUE TITLE
Client isnt grabbing osrs

### ISSUE THREAD

**Issue by to-forgive** [runelite/launcher#68]
Hi, i haven't played runescape in a while and came back and downloaded and installed Runelite to continue my adventure. I was able to load up fine until i logged into my runlite account on the client. The client immediately froze. I restarted the client and the game just never shows up. I can navigate Runelites client side.

[![Screenshot from Gyazo](https://gyazo.com/726534e8004395ab5f72567410a6c744/raw)](https://gyazo.com/726534e8004395ab5f72567410a6c744)

**Comment by Alexsuperfly** [comment]
1) this is an issue for the client
2) one has already been made for that runelite/runelite#9993
