### ISSUE TITLE
Launcher not detecting membership

### ISSUE THREAD

**Issue by Mad-Hattrr** [runelite/launcher#78]
RL will often not let me log in to a members world when I launch it for the first time that day, and ask me to switch to a free one. I usually resolve this issue by re-launching it. Is this an issue on my end?

**Comment by Nightfirecat** [comment]
RuneLite has no effect on whether you are able to log in to a member's world with your account. I recommend double-checking the account you're logging in with and possibly filing a support ticket with OSRS's support team.

**Comment by Mad-Hattrr** [comment]
Thanks for the reply! I'll file a support ticket and close this issue. If the support team can't find something on their end and this persists, I'll inquire once more with more details on my specs/RL version.
