### ISSUE TITLE
Runelite 1.3.0.1 windows build does not open

### ISSUE THREAD

**Issue by MattyJacques** [runelite/launcher#8]
I just downloaded and installed the most recent windows build release. When the installed application is opened, nothing happens. There is no flicker of something opening and closing, nothing at all. Process also does no show up in the task manager.

OS is Windows 10 version 1709

After running with --console I get this message:

> Error code [193] when trying to load jvm.dll: %1 is not a valid Win32 application.

I've tried reinstalling java and reinstalling RuneLite. The RuneLite.jar works perfectly fine, it is just through the launcher.

**Comment by Adam-** [comment]
What happens if you copy msvcr100.dll from RuneLite\jre\bin to RuneLite\?

**Comment by MattyJacques** [comment]
Then the .exe works as intended, what do you think could cause that?

**Comment by Adam-** [comment]
It is not placed there and it should be. Someone else was having this problem some days ago and so I did it https://github.com/runelite/launcher/commit/731c3a663f5694b6a376685b3817f74124f6a07a but did not build a new release. It is due to not having the VS runtimes on your system.

**Comment by Adam-** [comment]
Fixed in 1.4.3.
