### ISSUE TITLE
Continue Providing .jar

### ISSUE THREAD

**Issue by rushsteve1** [runelite/launcher#95]
Hello, I was wondering if it was possible to continue providing the `.jar` file in releases.
I maintain the RuneLite Flatpak and it depends on pulling the JAR file from the releases page. (Yes I'm aware this happened months ago and I just noticed...)

**Comment by Adam-** [comment]
We've not stopped providing jars, the 2.1.6 release just has no changes to the jar, and so one was not uploaded.

**Comment by rushsteve1** [comment]
Ah, thanks for the info then. Sorry to bother you.
