### ISSUE TITLE
Launcher says it hasnt updated to support the game.

### ISSUE THREAD

**Issue by Terrorfist** [runelite/launcher#97]
![Screenshot (1)](https://user-images.githubusercontent.com/82513288/114704111-8c8b5300-9d69-11eb-89b5-e96c6e43d30e.png)

 Can I fix this or am i just going to have to wait?

**Comment by Terrorfist** [comment]
I dont want to reinstall because I dont want to lose my custom plugins and settings, but it seems like ive already lost them.

**Comment by BehrRiley** [comment]
When the game updates (normally on Wednesdays), RuneLite can break temporarily. This is usually fixed shortly after when there's a released update to RuneLite. After the update has been made (usually announced in `#announcements` via the discord: https://runelite.net/discord), simply restart RuneLite to automatically get the new update.
